name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}   # <— ВАЖНО: путь к корню репозитория
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt

      - name: Lint (flake8)
        run: flake8 src tests

      - name: Format check (black)
        run: black --check src tests

      - name: Run unit tests (pytest)
        run: pytest -q

      - name: Data validation (Pandera) on tiny sample
        run: |
          python - << 'PY'
          import pandas as pd
          from pathlib import Path
          Path("data/processed").mkdir(parents=True, exist_ok=True)

          cols = ["ID","LIMIT_BAL","SEX","EDUCATION","MARRIAGE","AGE",
                  "PAY_0","PAY_2","PAY_3","PAY_4","PAY_5","PAY_6",
                  "BILL_AMT1","BILL_AMT2","BILL_AMT3","BILL_AMT4","BILL_AMT5","BILL_AMT6",
                  "PAY_AMT1","PAY_AMT2","PAY_AMT3","PAY_AMT4","PAY_AMT5","PAY_AMT6","target"]

          # train: 2 разные строки, ID в низком диапазоне
          train = pd.DataFrame([
              [1, 20000.0, 1, 2, 1, 30, 0,0,0,0,0,0,  0,0,0,0,0,0,   0,0,0,0,0,0, 0],
              [2, 30000.0, 2, 2, 1, 35, 0,0,0,0,0,0, 10,0,0,0,0,0,   0,0,0,0,0,0, 1],
          ], columns=cols)

          # test: 2 разные строки, ID в другом диапазоне (чтобы не было утечки)
          test = pd.DataFrame([
              [101, 25000.0, 1, 2, 1, 32, 0,0,0,0,0,0,  0,0,0,0,0,0,   0,0,0,0,0,0, 0],
              [102, 15000.0, 2, 3, 2, 28, 0,0,0,0,0,0,  5,0,0,0,0,0,   0,0,0,0,0,0, 0],
          ], columns=cols)

          train.to_csv("data/processed/train.csv", index=False)
          test.to_csv("data/processed/test.csv", index=False)

          from src.data.quality_report import main
          main("data/processed/train.csv","data/processed/test.csv","data/processed/data_quality_report.json")
          print("Validation OK")
          PY
